# @package _global_
model:
  charset_train: "0123456789\"'‘’“”—–,.:;`?-‾_!#$%&()*+/<=>@[]^{|}~\\।॥ঀঁংঃঅআইঈউঊঋঌএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ়ঽািীুূৃৄেৈোৌ্ৎৗড়ঢ়য়ৠৡৢৣ০১২৩৪৫৬৭৮৯ৰৱ৲৳৴৵৶৷৸৹৺৻ৼ৽ \u200c\u200d"
  charset_test: "0123456789\"'‘’“”—–,.:;`?-‾_!#$%&()*+/<=>@[]^{|}~\\।॥ঀঁংঃঅআইঈউঊঋঌএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ়ঽািীুূৃৄেৈোৌ্ৎৗড়ঢ়য়ৠৡৢৣ০১২৩৪৫৬৭৮৯ৰৱ৲৳৴৵৶৷৸৹৺৻ৼ৽ \u200c\u200d"
