# @package _global_
# contains charsets: oriya and kannada 
model:
  charset_train: "‌‍ !\"#$%&'()*+,-./0123456789:;<=>?@[\\]^_{|}~ಂಃ಄ಅಆಇಈಉಊಋಌಎಏಐಒಓಔಕಖಗಘಙಚಛಜಝಞಟಠಡಢಣತಥದಧನಪಫಬಭಮಯರಱಲಳವಶಷಸಹ಼ಽಾಿೀುೂೃೄೆೇೈೊೋೌ್ೕೖೝೞೠೡೢೣ೦೧೨೩೪೫೬೭೮೯ଁଂଃଅଆଇଈଉଊଋଌଏଐଓଔକଖଗଘଙଚଛଜଝଞଟଠଡଢଣତଥଦଧନପଫବଭମଯରଲଳଵଶଷସହ଼ଽାିୀୁୂୃୄେୈୋୌ୍॒୕ୖୗଡ଼ଢ଼ୟୠୡୢୣ।॥୦୧୨୩୪୫୬୭୮୯୰ୱ୲୳୴୵୶୷"
  charset_test: "‌‍ !\"#$%&'()*+,-./0123456789:;<=>?@[\\]^_{|}~ಂಃ಄ಅಆಇಈಉಊಋಌಎಏಐಒಓಔಕಖಗಘಙಚಛಜಝಞಟಠಡಢಣತಥದಧನಪಫಬಭಮಯರಱಲಳವಶಷಸಹ಼ಽಾಿೀುೂೃೄೆೇೈೊೋೌ್ೕೖೝೞೠೡೢೣ೦೧೨೩೪೫೬೭೮೯ଁଂଃଅଆଇଈଉଊଋଌଏଐଓଔକଖଗଘଙଚଛଜଝଞଟଠଡଢଣତଥଦଧନପଫବଭମଯରଲଳଵଶଷସହ଼ଽାିୀୁୂୃୄେୈୋୌ୍॒୕ୖୗଡ଼ଢ଼ୟୠୡୢୣ।॥୦୧୨୩୪୫୬୭୮୯୰ୱ୲୳୴୵୶୷"
