# @package _global_
model:
  charset_train: "0123456789\"'‘’“”°,.…:;?-–_!#$%&()*+/<=>@[]^{|}~ \\।॥ಂಃ಄ಅಆಇಈಉಊಋಌಎಏಐಒಓಔಕಖಗಘಙಚಛಜಝಞಟಠಡಢಣತಥದಧನಪಫಬಭಮಯರಱಲಳವಶಷಸಹ಼ಽಾಿೀುೂೃೄೆೇೈೊೋೌ್ೕೖೝೞೠೡೢೣ೦೧೨೩೪೫೬೭೮೯ \u200c\u200d\u0952"
  charset_test:  "0123456789\"'‘’“”°,.…:;?-–_!#$%&()*+/<=>@[]^{|}~ \\।॥ಂಃ಄ಅಆಇಈಉಊಋಌಎಏಐಒಓಔಕಖಗಘಙಚಛಜಝಞಟಠಡಢಣತಥದಧನಪಫಬಭಮಯರಱಲಳವಶಷಸಹ಼ಽಾಿೀುೂೃೄೆೇೈೊೋೌ್ೕೖೝೞೠೡೢೣ೦೧೨೩೪೫೬೭೮೯ \u200c\u200d\u0952"









