# @package _global_
model:
  charset_train: "ਁਂਃਭਅਆਇਈਉਊ‌ਏਐਓਔਕਖਗਘਙਚਛਜਝਞਟ !\"#$%&'()*+,-./0123456789:;<=>?@ਸਹ਼ਾਿੀੁੂੇੈੋੌਰ੍ੑਖ਼ਗ਼[\\]^_`ਜ਼ੜਫ਼੦੧੨੩੪੫੬੭੮੯ੰੱੲੳੴੵ{|}~ਲਮਲ਼ਦ­ਥਵਸ਼ਠਡਢऀँंःऄअआइईउऊऋऌऍऎएऐऑऒओऔकखगघङचछजझञटठडढणतथदधनऩपफबभमयरऱलळऴवशषसहऺऻ़ऽािीुूृॄॅॆेैॉॊोौ्ॎॏॐ॒॑॓॔ॕॖॗक़ख़ग़ज़ड़ढ़फ़य़ॠॡॢॣ।॥०१२३४५६७८९॰ॱॲॳॴॵॶॷॸॹॺॻॼॽॾॿਯਨਧਤਪਣਫਬ"
  charset_test: "ਁਂਃਭਅਆਇਈਉਊ‌ਏਐਓਔਕਖਗਘਙਚਛਜਝਞਟ !\"#$%&'()*+,-./0123456789:;<=>?@ਸਹ਼ਾਿੀੁੂੇੈੋੌਰ੍ੑਖ਼ਗ਼[\\]^_`ਜ਼ੜਫ਼੦੧੨੩੪੫੬੭੮੯ੰੱੲੳੴੵ{|}~ਲਮਲ਼ਦ­ਥਵਸ਼ਠਡਢऀँंःऄअआइईउऊऋऌऍऎएऐऑऒओऔकखगघङचछजझञटठडढणतथदधनऩपफबभमयरऱलळऴवशषसहऺऻ़ऽािीुूृॄॅॆेैॉॊोौ्ॎॏॐ॒॑॓॔ॕॖॗक़ख़ग़ज़ड़ढ़फ़य़ॠॡॢॣ।॥०१२३४५६७८९॰ॱॲॳॴॵॶॷॸॹॺॻॼॽॾॿਯਨਧਤਪਣਫਬ"
