# @package _global_
model:
  charset_train: "0123456789\"'“‘’”,.¸:;?­—–-_!#$%&()*+/<=>@[]^{|}~ \\।॥ஂஃஅஆஇஈஉஊஎஏஐஒஓஔகஙசஜஞடணதநனபமயரறலளழவஶஷஸஹாிீுூெேைொோௌ்ௐௗ௦௧௨௩௪௫௬௭௮௯௰௱௲௳௴௵௶௷௸௹௺"
  charset_test: "0123456789\"'“‘’”,.¸:;?­—–-_!#$%&()*+/<=>@[]^{|}~ \\।॥ஂஃஅஆஇஈஉஊஎஏஐஒஓஔகஙசஜஞடணதநனபமயரறலளழவஶஷஸஹாிீுூெேைொோௌ்ௐௗ௦௧௨௩௪௫௬௭௮௯௰௱௲௳௴௵௶௷௸௹௺"


