# @package _global_
model:
  charset_train: "0123456789\"'،,.؛:;؟?-_!#$%&()*+/<=>@[]^{|}~ \\।أﺐﻨﻭﺗﻔﻢ۔پں ڈ تب ۓضدھچ  ٹ ظ جھم ےض ن گئڑژ ڑ ل ا ٹء صپھث ہ لسق حغۃ  ‍ءتھژھة  ‍بةطبھس ٘دذح نا   یٹھکہشکھآ ذ ک ۂیھد گھںفجعڈٔرھر ظئےرمھوقــِص ز زط ج پ مغ ف ع ش نھلھؤۃثۂ  ‍گ وھچآخ "
  charset_test: "0123456789\"'،,.؛:;؟?-_!#$%&()*+/<=>@[]^{|}~ \\।أﺐﻨﻭﺗﻔﻢ۔پں ڈ تب ۓضدھچ  ٹ ظ جھم ےض ن گئڑژ ڑ ل ا ٹء صپھث ہ لسق حغۃ  ‍ءتھژھة  ‍بةطبھس ٘دذح نا   یٹھکہشکھآ ذ ک ۂیھد گھںفجعڈٔرھر ظئےرمھوقــِص ز زط ج پ مغ ف ع ش نھلھؤۃثۂ  ‍گ وھچآخ "


